dataset_name: "twitter"

data_params:
  data_root: "/home/public/pc/Mobile-Search-Engine/.datasets/twitter_imgs"
  annotation_file: "/home/public/pc/Mobile-Search-Engine/.datasets/tweets_images_texts.txt"
  image_size: 224
  num_classes: 100
  text_prompt: "a photo of {}."
  img_dict_path: "/home/public/pc/Mobile-Search-Engine/.datasets/twitter_img_dict.pkl"

default_params:
  lora_dir: "/home/public/pc/Mobile-Search-Engine/.checkpoints/lora/twitter/with_head/trunk/e50"
  embeddings_path: "parameters/image/twitter"
  version: "twitter"
  topk_values: [1, 5, 10, 20, 30, 40] 